EXCEPTIONS = {
    "fall to the ground": {"verb": "fall", "object": "the athlete"},
    "add butter, hot sauce, pepper, garlic powder, melted butter, and mix butter": {
        "verb": "mix",
        "object": "butter, hot sauce, pepper, garlic powder and melted butter",
    },
    "add potato mixture to wrapper and seal shut": {
        "verb": "shut",
        "object": "wrapper",
    },
    "add the lettuce and radicchio to bowl with the dressing and mix together": {
        "verb": "mix",
        "object": "lettuce, radicchio and dressing",
    },
    "beat two eggs into the milk and whisk in a cup of melted butter": {
        "verb": "whisk",
        "object": "two eggs",
    },
    "boil the wrapped pierogies in boiling salted water": {
        "verb": "boil",
        "object": "salted water",
    },
    "chop 2 garlic cloves grate ginger about 2 tsp and green onions finely": {
        "verb": "chop",
        "object": "the garlic, the ginger, and the onions",
    },
    "chop some red onions, red pepper, and green pepper into square pieces', 'some red onions, red pepper, and green pepper into square pieces": {
        "verb": "chop",
        "object": "chop some red onions, red pepper, and green pepper into square pieces.', 'red onions, red pepper, and green pepper",
    },
    "close the front door or cover of the printer": {
        "verb": "close",
        "object": "the front door of the printer",
    },
    "close the sluice and empty and disconnect the water pipe": {
        "verb": "unplug",
        "object": "the water pipe",
    },
    "combine the cheeses, mustard, paprika, and pepper in a small bowl": {
        "object": "the cheeses, mustard, paprika, and pepper",
        "verb": "combine",
    },
    "crack and fry the eggs": {"verb": "crack", "object": "the eggs"},
    "drain the spaghetti then mix it with the pancetta egg and cream": {
        "verb": "mix",
        "object": "the spaghetti",
    },
    "drizzle the dressing on the salad and toss to combine": {
        "verb": "mix",
        "object": "the dressing and the salad",
    },
    "fill the taco shells and top with sour cream, grated cheddar cheese, and chopped lettuce', 'the taco shells and top": {
        "verb": "fill",
        "object": "the taco shells",
    },
    "fill the tree into the pit": {"verb": "fill", "object": "the pit"},
    "fix the wind mill on the bracket": {"verb": "fix", "object": "the windmill"},
    "heat the teapot and wash the cup": {"verb": "wash", "object": "the cup"},
    "melt the wax with water": {"verb": "melt", "object": "the wax"},
    "mix 3 tsps of corn starch with water": {
        "verb": "mix",
        "object": "corn starch and water",
    },
    "mix hot pepper flakes, hot chili paste, and soy sauce": {
        "verb": "mix",
        "object": "hot pepper flakes, hot chili paste, and soy sauce",
    },
    "mix melted butter with the batter": {"verb": "mix", "object": "butter and batter"},
    "mix some parmesan cheese and pepper with the eggs in a bowl": {
        "verb": "mix",
        "object": "cheese, pepper, and eggs",
    },
    "mix the cheese with pepperoni": {
        "verb": "mix",
        "object": "the cheese and the pepperoni",
    },
    "now add the chopped shrimps and stir until the shrimp is combined with the mixture well', 'the chopped shrimps": {
        "verb": "combine",
        "object": "the shrimps and the mixture",
    },
    "open the front door or cover of the printer": {
        "verb": "open",
        "object": "the front door of the printer",
    },
    "open the lid stir and season": {"verb": "open", "object": "the lid"},
    "peel and chop the carrots into pieces": {"verb": "chop", "object": "the carrots"},
    "place the filling in the middle of the wonton wrapper and fold shut with egg": {
        "verb": "shut",
        "object": "the wonton wrapper",
    },
    "pour some barbecue sauce on the meat loaf and bake the meatloaf": {
        "verb": "pour",
        "object": "the barbecue sauce",
    },
    "prepare and boil water": {"verb": "boil", "object": "water"},
    "put the chicken pieces in an oven for about 10 minutes until cheese to melt": {
        "verb": "melt",
        "object": "the cheese",
    },
    "screw and fix the cover": {"verb": "screw", "object": "the cover"},
    "screw off the screws used to fix the switch": {
        "verb": "screw",
        "object": "the switch",
    },
    "soak and wash the rice": {"verb": "wash", "object": "the rice"},
    "stir the bowl until all the ingredients are combined": {
        "verb": "combine",
        "object": "the ingredients",
    },
    "tear off the front of the sticker": {"verb": "tear", "object": "the sticker"},
    "tear off the other side of the sticker": {"verb": "tear", "object": "the sticker"},
    "unscrew the screws used to fix the screen": {
        "verb": "unscrew",
        "object": "the screw",
    },
    "use the needle to open the SIM card slot": {
        "verb": "open",
        "object": "the SIM card slot",
    },
    "wet and wash hands": {"verb": "wash", "object": "the hands"},
    "wet and wash the hair": {"verb": "wash", "object": "the hair"},
    "mince cabbage and chop some green onions": {
        "verb": "chop",
        "object": "the onions",
    },
    "put the melted soap block into the vessel": {
        "verb": "fill",
        "object": "the vessel",
    },
    "add some cleaner to clean and wet the lenses and take out the lenses": {
        "verb": "clean",
        "object": "the lenses",
    },
    "mix in salt and pepper.": {"verb": "mix", "object": "salt and pepper"},
    "banknote falling like a feather or paper": {"verb": "fall", "object": "banknote"},
    "spoon falling like a rock": {"verb": "fall", "object": "spoon"},
    "stamp falling like a rock": {"verb": "fall", "object": "stamp"},
    "pour the tea into the vessel": {"verb": "pour", "object": "tea"},
    "pour the egg into the pot": {"verb": "fill", "object": "pot"},
    "pour the ingredients into the bowl": {"verb": "fill", "object": "bowl"},
    "pour oil into the wok": {"verb": "fill", "object": "wok"},
    "pour raw materials": {"verb": "fill", "object": "bowl"},
    "pour the wax into the vessel": {"verb": "fill", "object": "vessel"},
    "pour the mixture on the meat loaf": {"verb": "pour", "object": "mixture"},
    "pour some oil into a hot pan": {"verb": "fill", "object": "pan"},
    "pour wine over the snails in a bowl": {"verb": "fill", "object": "bowl"},
    "pour the butter into the egg yolks": {
        "verb": "mix",
        "object": "butter and egg yolks",
    },
    "pour oil into a hot pan and add chopped onions and laksa sauce": {
        "verb": "fill",
        "object": "pan",
    },
    "pour the soup on bean sprouts and sprinkle parsley on top": {
        "verb": "fill",
        "object": "bowl",
    },
    "pour the cooking oil into the wok and add curry powder": {
        "verb": "fill",
        "object": "wok",
    },
    "pour the marinade onto the chicken and mix": {
        "verb": "mix",
        "object": "marinade and chicken",
    },
    "pour buttermilk and hot sauce on the chicken.": {
        "verb": "mix",
        "object": "buttermilk, hot sauce and chicken",
    },
    "cut a certain length": {"verb": "cut", "object": "cable"},
    "add some lemon grass, fish sauce, sugar, salt, chicken powder, chilli flakes, and stir it to combine": {
        "verb": "combine",
        "object": "lemon grass and the fish sauce",
    },
    "combine the milk with the flour": {
        "verb": "combine",
        "object": "the milk and the flour",
    },
    "combine pepper sauce and melted butter in a bowl": {
        "verb": "combine",
        "object": "the pepper sauce and the butter",
    },
    "combine diced toamto and cucumber and sliced onions": {
        "verb": "combine",
        "object": "the onions, the cucumber and the tomato",
    },
    "fill second pot with peas, mint, salt, sugar, and water and boil": {
        "verb": "fill",
        "object": "the pot",
    },
    "fill the taco shells and top with sour cream, grated cheddar cheese, and chopped lettuce": {
        "verb": "fill",
        "object": "the taco shells",
    },
    "mix some cumin, cinnamon, black pepper, and paprika": {
        "verb": "mix",
        "object": "cumin, cinnamon, black pepper, and paprika",
    },
    "mix paprika and pepper with the meat": {
        "verb": "mix",
        "object": "parika, pepper and meat",
    },
    "mix soy sauce, sesame oil, sugar, finely chopped spring onions, and minced garlic": {
        "verb": "mix",
        "object": "flour, baking soda, salt, and sugar",
    },
    "mix together an egg, butter, and butter milk": {
        "verb": "mix",
        "object": "egg, butter, and butter milk",
    },
    "mix the lettuce with the sauce dressing and add parmesan cheese": {
        "verb": "mix",
        "object": "the lettuce and the dressing",
    },
    "mix the breadcrumbs with the meat": {
        "verb": "mix",
        "object": "the breadcrums and the meat",
    },
    "mix flour, ghee, and salt together": {
        "verb": "mix",
        "object": "flour, ghee, and salt",
    },
    "mix hot sauce and melted butter together": {
        "verb": "mix",
        "object": "sauce and butter",
    },
    "add korean red chili pepper flakes to the mixture and mix with hand": {
        "verb": "mix",
        "object": "chili pepper flakes and mixture",
    },
    "mix swiss cheddar and monterey jack cheese together in a bowl": {
        "verb": "mix",
        "object": "cheddar and cheese",
    },
    "mix ingredients in the bowl using a fork": {
        "verb": "mix",
        "object": "ingredients",
    },
    "add flour, cornmeal, sugar, salt, and baking soda to bowl and mix": {
        "verb": "mix",
        "object": "flour, cornmeal, sugar, salt, and soda",
    },
    "add flour, paprika, garlic powder, black pepper, and salt to a bag and mix together": {
        "verb": "mix",
        "object": "flour, paprika, garlic powder, pepper, and salt",
    },
    "drain the spaghetti then mix it with the pancetta egg and cream": {
        "verb": "mix",
        "object": "the spaghetti, the pancetta, and the cream",
    },
    "close the sluice and empty and disconnect the water pipe": {
        "verb": "close",
        "object": "the sluice",
    },
    "tear the dried seaweed into smaller pieces and put them on a plate": {
        "verb": "cut",
        "object": "the seaweed",
    },
    "fix the new string on the head of the guitar": {
        "verb": "fix",
        "object": "guitar string",
    },
    "clean up the interior of thepumpkin": {"verb": "clean", "object": "the pumpkin"},
    "slice the potato pumpkin and eggplant": {
        "verb": "slice",
        "object": "the potato, the pumpkin and the egglpant",
    },
    "slice the fish cakes, bean curd, and boiled eggs": {
        "verb": "slice",
        "object": "the fish cakes",
    },
    "slice the tomatoes onions and pickles": {
        "verb": "slice",
        "object": "the tomateos, the onions, and the pickles",
    },
    "slice a piece of cucumber and add with the salmon": {
        "verb": "slice",
        "object": "the cucumber",
    },
    "screw off the screws and sheetmetals and baffles on the both sides of the CD drive": {
        "verb": "screw",
        "object": "the sheetmetals",
    },
    "use screwdriver or electirc screwdriver to screw the wire in the wall into the screw of the new switch": {
        "verb": "screw",
        "object": "the wire",
    },
    "dropping ear plug carrying case in front of a water bottle": {
        "verb": "fall",
        "object": "earplug carrying case",
    },
    "attaching mobile charger to plug socket": {
        "verb": "plug",
        "object": "the mobile charger and the plug socket",
    },
    "crack 2 eggs in a bowl": {"verb": "crack", "object": "the eggs"},
    "crack two eggs in a bowl": {"verb": "crack", "object": "the eggs"},
    "crack one egg in a bowl": {"verb": "crack", "object": "the egg"},
    "drop all the meatballs into the boiling pot of sauce and cook": {
        "verb": "drop",
        "object": "the meatballs",
    },
    "add apple sauce black pepper and sesame oil and whisk everything together": {
        "verb": "mix",
        "object": "the apple sauce, the pepper, and the sesame oil",
    },
    "add an egg and some milk and whisk everything quickly": {
        "verb": "mix",
        "object": "the egg and the milk",
    },
    "separate the egg white and egg yolk and whisk the egg whites": {
        "verb": "divide",
        "object": "the egg white and the egg yolk",
    },
    "add dijon mustard milk and salt to eggs and whisk it": {
        "verb": "mix",
        "object": "the milk and the eggs",
    },
    "beat an egg in a bowl and whisk some milk with it": {
        "verb": "mix",
        "object": "the eggs and the milk",
    },
    "break three eggs and add a little cream": {"verb": "break", "object": "the eggs"},
    "matchbox falling like a rock": {"verb": "fall", "object": "matchbox"},
    "pour it into a glass": {"verb": "fill", "object": "glass"},
    "pour into a glass": {"verb": "fill", "object": "glass"},
    "add in some flour and milk and whisk it": {
        "verb": "mix",
        "object": "flour and milk",
    },
    "lifting wood log up completely, then letting it drop down": {
        "verb": "fall",
        "object": "wood log",
    },
    "lifting glue stick up completely, then letting it drop down": {
        "verb": "fall",
        "object": "glue stick",
    },
    "lifting book up completely, then letting it drop down": {
        "verb": "fall",
        "object": "book",
    },
    "lifting firm plastic up completely, then letting it drop down": {
        "verb": "fall",
        "object": "firm plastic",
    },
    "lifting usb stick up completely, then letting it drop down": {
        "verb": "fall",
        "object": "usb stick",
    },
    "lifting sketch pen up completely, then letting it drop down": {
        "verb": "fall",
        "object": "sketch pen",
    },
    "lifting set of compasses up completely, then letting it drop down": {
        "verb": "fall",
        "object": "compasses",
    },
    "lifting candle up completely, then letting it drop down": {
        "verb": "fall",
        "object": "candle",
    },
    "lifting box tape up completely, then letting it drop down": {
        "verb": "fall",
        "object": "box tape",
    },
    "lifting hose head up completely, then letting it drop down": {
        "verb": "fall",
        "object": "hose head",
    },
    "lifting note pad up completely, then letting it drop down": {
        "verb": "fall",
        "object": "note pad",
    },
    "plugging mains plug into socket": {"verb": "plug", "object": "mains plug"},
    "wash and slice the prawn and add it to the meat": {
        "verb": "slice",
        "object": "the prawn",
    },
    "pour in the prepared dressing and mix again to serve": {
        "verb": "mix",
        "object": "the dressings",
    },
    "mix in cheese": {"verb": "mix", "object": "cheese"},
    "mix in flour": {"verb": "mix", "object": "flour"},
    "mix in tamarind paste": {"verb": "mix", "object": "tamarind paste"},
    "flush and wash the interior": {"verb": "wash", "object": "interior"},
    "separate and cut the chicken wing at the two joints": {
        "verb": "cut",
        "object": "chicken wing",
    },
    "roll dough flat and cut into circles": {"verb": "cut", "object": "dough"},
    "throwing throwing lighter in the air and letting it fall": {
        "verb": "fall",
        "object": "lighter",
    },
    "whisk the eggs": {"verb": "whisk", "object": "egg yolk and egg white"},
}


EXCLUDED = [
    """
  TODO: COS to remove: bake, 
  """
    "add tomato puree and cook until it starts to lose oil",
    "after cooking mix well to incorporate cheese and then bake",
    "bake it in the oven for 10 minutes and they are ready to serve",
    "bake the bread in an oven",
    "brush each pizza bite with some melted butter and sprinkle some italian seasoning on top",
    "clean up and soak",
    "cut in half",
    "cut into small pieces",
    "cut into strips",
    "cut into strips and pieces",
    "cut a hole",
    "cut out a hole",
    "cut along the edges",
    "find the position of the hole",
    "fill with some soil",
    "pour in after mix it",
    "mix in sour cream",
    "leave the jars at the room temperature closing the lids not too tight for 5-6 days"
    "once it is cooled, add the chopped onions, grated cheddar, yougart, salt, pepper, and melted butter and mix well",
    "package and freeze",
    "place the tray under broiler and bake the meat balls until well browned"
    "pour in after mix it",
    "pour the noodles into the water and stir",
    "pour the cooked noodles",
    "put some of the vegetables in to the pot and let it come to boil by slightly separating the noodles",
    "reset the switch and screw on the screws used to fix the switch",
    "reveal the glue from the face",
    "roll it up brush some paste on edge and close it to a roll",
    "use vacuum cleaner to clean",
    "melt the soap block",
    "pour some barbecue sauce on the meat loaf and bake the meatloaf",
    "prepare and boil water",
    "boil water or coffee",
    "tilting plan sheet with rubber on it slightly so it doesn't fall down",
    "trying to pour water into bottle, but missing so it spills next to it"
    "spoon colliding with spoon and both are being deflected",
    "a water can colliding with another water can and both are being deflected",
    "pour some glue to the face",
    "pour the sauce on top of the egg",
    "pour half of the liquid to the mixed vegetable",
    "toss everything well to combine",
    "combine flour, sugar, polenta, baking powder, egg, and milk",
    "mix soy sauce, sesame oil, sugar, finely chopped spring onions, and minced garlic",
    "add salt and garlic, powder seasoning, black pepper powder to the flour and mix well",
    "add cumin powder, red chili powder, and garlic powder and mix it well",
    "mix chicken breast, apple grape, celery, lemon juice, cream together and season with black pepper and salt."
    "fold the squares inward and fix them",
    "slice it diagonally and serve",
    "mix the cooked bulgur wheat, boiled chickpeas, diced tomato, cucumber, leeks, and parsley",
    "lifting up one end of table without letting it drop down",
    "lifting jar up completely without letting it drop down",
    "lifting flashlight up completely without letting it drop down",
    "lifting up one end of box without letting it drop down",
    "lifting up one end of pencil without letting it drop down",
    "lifting up one end of a booklet without letting it drop down",
    "add anchovy paste worcestershire sauce olive oil and parmesan cheese and whisk it.",
    "pour into the ingredients",
    "moving moving something and close each other closer to each other",
    "cut off and remove the old string",
    "anchovy paste worcestershire sauce olive oil and parmesan cheese",
]

# copy-pasted from https://englishstudyonline.org/intransitive-verb/
INTRANSITIVE = [
    "agree",
    "appear",
    "arrive",
    "become",
    "belong",
    "collapse",
    "consist",
    "cost",
    "cough",
    "cry",
    "depend",
    "die",
    "disappear",
    "emerge",
    "exist",
    "explode",
    "fade",
    "fall",
    "fast",
    "float",
    "fly",
    "gallop",
    "go",
    "grow",
    "happen",
    "have",
    "inquire",
    "jump",
    "kneel",
    "laugh",
    "lead",
    "lean",
    "leap",
    "learn",
    "left",
    "lie",
    "limp",
    "listen",
    "live",
    "look",
    "march",
    "mourn",
    "move",
    "occur",
    "panic",
    "party",
    "pause",
    "peep",
    "pose",
    "pounce",
    "pout",
    "pray",
    "preen",
    "read",
    "recline",
    "relax",
    "relent",
    "remain",
    "respond",
    "result",
    "revolt",
    "rise",
    "roll",
    "run",
    "rush",
    "sail",
    "scream",
    "shake",
    "shout",
    "sigh",
    "sit",
    "skip",
    "sleep",
    "slide",
    "smell",
    "smile",
    "snarl",
    "sneeze",
    "soak",
    "spin",
    "spit",
    "sprint",
    "squeak",
    "stagger",
    "stand",
    "stay",
    "swim",
    "swing",
    "twist",
    "vanish",
    "vomit",
    "wade",
    "wait",
    "wake",
    "walk",
    "wander",
    "wave",
    "whirl",
    "wiggle",
    "work",
    "yell",
]
