EXCEPTIONS = {
    "bent the paperclips by hands": {"verb": "bend", "object": "the paperclips"},
    "pull out the needle and press with cotton": {
        "verb": "pull out",
        "object": "the needle",
    },
    "ski up from the hill": {"verb": "ascend", "object": "the athlete"},
    "place license plate": {"verb": "attach", "object": "the license plate"},
    "turn off the balde screw": {"verb": "unscrew", "object": "the balde screw"},
    "apply the cleaning agent with towel evenly": {
        "verb": "apply",
        "object": "the cleaning agent",
    },
    "unfolding towel": {"verb": "unfold", "object": "the towel"},
    "unfoliong leaf": {"verb": "unfold", "object": "the leaf"},
    "screw on the screw": {"verb": "screw", "object": "the screws"},
    "cone the leaves": {"verb": "fold", "object": "the leaves"},
    "power off": {"verb": "turn off", "object": "the laptop"},
    "wrap on the tape": {"verb": "wrap", "object": "the leg"},
    "stuffing used gloves into a box": {"verb": "insert", "object": "the gloves"},
    "do the first two jumps": {"verb": "jump", "object": "the athlete"},
    "wipe off the cleaning agent": {"verb": "remove", "object": "the cleaning agent"},
    "take out after freezing": {"verb": "take out", "object": "the soap"},
    "pour the orange jouce into the cup": {"verb": "fill", "object": "the cup"},
    "pour the egg into the bowl": {"verb": "fill", "object": "the bowl"},
    "remove the light shell/housing/support": {"verb": "remove", "object": "the light"},
    "mix everything well in the bowl": {"verb": "mix", "object": "the ingredients"},
    "take out the quilt cover from antoher side": {
        "verb": "take out",
        "object": "the quilt cover",
    },
    "ski down from the hill": {"verb": "ski", "object": "the skier"},
    "paint on the paper": {"verb": "paint", "object": "the paper"},
    "paint on sugar": {"verb": "paint", "object": "the sugar"},
    "a slice of bread falling like a rock": {"verb": "fall", "object": "the bread"},
    "pen falling like a rock": {"verb": "fall", "object": "the pen"},
    "blue toy building block falling like a rock": {
        "verb": "fall",
        "object": "the toy building block",
    },
    "green toy alligator falling like a rock": {
        "verb": "fall",
        "object": "the toy alligator",
    },
    "yellow balpen falling like a rock": {"verb": "fall", "object": "the balpen"},
    "foam packaging falling like a feather or paper": {
        "verb": "fall",
        "object": "the foam packaging",
    },
    "plastic seal falling like a rock": {"verb": "fall", "object": "the plastic seal"},
    "close switch": {"verb": "close", "object": "the switch"},
    "uncovering remote": {"verb": "uncover", "object": "the remote"},
    "digging scale out of rice": {"verb": "dig up", "object": "the scale"},
    "unfolding meter scale": {"verb": "unfold", "object": "the meter scale"},
    "place slices of canadian bacon onto a hot pan": {
        "verb": "insert",
        "object": "the bacon",
    },
    "cover with some soils": {"verb": "fill", "object": "the holes"},
    "apply the shampoo or the hair conditioner": {
        "verb": "apply",
        "object": "the shampoo",
    },
    "scratch the hair conditioner": {"verb": "clean", "object": "the head"},
    "install the back cover and waterproof ring": {
        "verb": "install",
        "object": "the back cover",
    },
    "use sandpaper/metal to polish rubber near leak": {
        "verb": "polish",
        "object": "the pipe",
    },
    "soak them into water": {"verb": "soak", "object": "the potatoes"},
    "wiping water off of the table": {"verb": "clean", "object": "the table"},
    "wiping foam soap off of counter": {"verb": "clean", "object": "the counter"},
    "wear the  contact lenses": {"verb": "put on", "object": "the contact lenses"},
    "moving pack across a surface until it falls down": {
        "verb": "drop",
        "object": "the pack",
    },
    "wear the contact lenses": {"verb": "put on", "object": "the contact lenses"},
    "Which object was tidied up by the person?": {
        "verb": "tidy up",
        "object": "the person",
    },
    "scratch the hair carefully": {"verb": "clean", "object": "the hair"},
    "pull open the stapler": {"verb": "open", "object": "the stapler"},
    "paper falling like a feather or paper": {"verb": "fall", "object": "the paper"},
    "put in the oil to fry": {"verb": "drop", "object": "the potatoes"},
    "uncovering a brooch rose": {"verb": "uncover", "object": "the brooch rose"},
    "plastic falling like a feather or paper": {
        "verb": "fall",
        "object": "the plastic",
    },
    "paper towel falling like a feather or paper": {
        "verb": "fall",
        "object": "the paper towel",
    },
    "soak them in water": {"verb": "soak", "object": "the potatoes"},
    "wiping water off of mirror": {"verb": "clean", "object": "the mirror"},
    "wiping chalk off of a mini chalkboard": {
        "verb": "clean",
        "object": "the chalkboard",
    },
    "stick handle to paper basket": {"verb": "attach", "object": "the handle"},
    "polish with polisher": {"verb": "clean", "object": "the car"},
    "lifting hair spray bottle up completely without letting it drop down": {
        "verb": "lift",
        "object": "the bottle",
    },
    "spray the cleaning agent on the car window": {
        "verb": "clean",
        "object": "the car window",
    },
    "pulling lavender glade spray out of pot": {
        "verb": "pull out",
        "object": "the spray",
    },
    "wiping sauce off of table": {"verb": "clean", "object": "the table"},
    "install the light shell/housing/support": {
        "verb": "screw",
        "object": "the light bulb",
    },
    "screw off the screws and sheetmetals and baffles on the both sides of the CD drive": {
        "verb": "unscrew",
        "object": "the screws",
    },
    "wrap in foil paper": {"verb": "wrap", "object": "the cable"},
    "cut a hole on the shell": {"verb": "divide", "object": "the chestnut"},
    "wipe the detergent": {"verb": "clean", "object": "the seat"},
    "apply detergent to bathtub": {"verb": "clean", "object": "the bathtub"},
    "use screwdriver or electirc screwdriver to release the wire in the wall from the switch": {
        "verb": "unplug",
        "object": "the wire",
    },
    "rub back and forth with potatoes or rust remover": {
        "verb": "clean",
        "object": "the pan",
    },
    "screw on the screws": {"verb": "screw", "object": "the screws"},
    "screw off the valve cap and open the valve": {
        "verb": "open",
        "object": "the valve",
    },
    "apply detergent": {"verb": "clean", "object": "the surface"},
    "use the body wash": {"verb": "clean", "object": "the animal"},
    "apply detergent to leather": {"verb": "clean", "object": "the leather"},
    "put on sofa cover": {"verb": "cover", "object": "the sofa"},
    "grind the coffee beans": {"verb": "destroy", "object": "the coffee beans"},
    "put the sheet on the bed": {"verb": "cover", "object": "the sheet"},
    "peel": {"verb": "cut", "object": "the fruit"},
    "place license plate cover": {"verb": "attach", "object": "the license plate"},
    "put on the hair extensions": {"verb": "wear", "object": "the hair extensions"},
    "reset and screw on the screws": {"verb": "screw", "object": "the screws"},
    "open cover": {"verb": "open", "object": "the cover"},
    "pour the soup in": {"verb": "fill", "object": "something"},
    "pour bean paste into plate": {"verb": "fill", "object": "the plate"},
    "blend the phone": {"verb": "disassemble", "object": "the phone"},
    "fall to the ground": {"verb": "fall", "object": "the athlete"},
    "rise to the sky": {"verb": "rise", "object": "the athlete"},
    "add butter, hot sauce, pepper, garlic powder, melted butter, and mix butter": {
        "verb": "mix",
        "object": "the butter, hot sauce, pepper, garlic powder and melted butter",
    },
    "add potato mixture to wrapper and seal shut": {
        "verb": "shut",
        "object": "the wrapper",
    },
    "add the lettuce and radicchio to bowl with the dressing and mix together": {
        "verb": "mix",
        "object": "the lettuce, radicchio and dressing",
    },
    "pour salt and rust removal liquid": {"verb": "fill", "object": "the pan"},
    "beat two eggs into the milk and whisk in a cup of melted butter": {
        "verb": "whisk",
        "object": "the two eggs",
    },
    "wipe screen again": {"verb": "wipe", "object": "the screen"},
    "boil the wrapped pierogies in boiling salted water": {
        "verb": "boil",
        "object": "the salted water",
    },
    "chop 2 garlic cloves grate ginger about 2 tsp and green onions finely": {
        "verb": "chop",
        "object": "the garlic, the ginger, and the onions",
    },
    "chop some red onions, red pepper, and green pepper into square pieces', 'some red onions, red pepper, and green pepper into square pieces": {
        "verb": "chop",
        "object": "the chop some red onions, red pepper, and green pepper into square pieces.', 'red onions, red pepper, and green pepper",
    },
    "close the front door or cover of the printer": {
        "verb": "close",
        "object": "the front door of the printer",
    },
    "close the sluice and empty and disconnect the water pipe": {
        "verb": "empty",
        "object": "the water pipe",
    },
    "combine the cheeses, mustard, paprika, and pepper in a small bowl": {
        "object": "the cheeses, mustard, paprika, and pepper",
        "verb": "combine",
    },
    "crack and fry the eggs": {"verb": "crack", "object": "the eggs"},
    "drain the spaghetti then mix it with the pancetta egg and cream": {
        "verb": "mix",
        "object": "the spaghetti",
    },
    "drizzle some oil on top some bread and heat them in a pan": {
        "verb": "wet",
        "object": "the bread",
    },
    "drizzle the dressing on the salad and toss to combine": {
        "verb": "mix",
        "object": "the dressing and the salad",
    },
    "fill the taco shells and top with sour cream, grated cheddar cheese, and chopped lettuce', 'the taco shells and top": {
        "verb": "fill",
        "object": "the taco shells",
    },
    "fill the tree into the pit": {"verb": "fill", "object": "the pit"},
    "fix the wind mill on the bracket": {"verb": "fix", "object": "the wind mill"},
    "heat the teapot and wash the cup": {"verb": "wash", "object": "the cup"},
    "melt the wax with water": {"verb": "melt", "object": "the wax"},
    "mix 3 tsps of corn starch with water": {
        "verb": "mix",
        "object": "the corn starch and water",
    },
    "mix hot pepper flakes, hot chili paste, and soy sauce": {
        "verb": "mix",
        "object": "the hot pepper flakes, hot chili paste, and soy sauce",
    },
    "mix melted butter with the batter": {
        "verb": "mix",
        "object": "the butter and batter",
    },
    "mix some parmesan cheese and pepper with the eggs in a bowl": {
        "verb": "mix",
        "object": "the cheese, pepper, and eggs",
    },
    "mix the cheese with pepperoni": {
        "verb": "mix",
        "object": "the cheese and the pepperoni",
    },
    "now add the chopped shrimps and stir until the shrimp is combined with the mixture well', 'the chopped shrimps": {
        "verb": "combine",
        "object": "the shrimps and the mixture",
    },
    "open the front door or cover of the printer": {
        "verb": "open",
        "object": "the front door of the printer",
    },
    "open the lid stir and season": {"verb": "open", "object": "the lid"},
    "peel and chop the carrots into pieces": {"verb": "chop", "object": "the carrots"},
    "place the filling in the middle of the wonton wrapper and fold shut with egg": {
        "verb": "shut",
        "object": "the wonton wrapper",
    },
    "pour some barbecue sauce on the meat loaf and bake the meatloaf": {
        "verb": "cover",
        "object": "the barbecue sauce",
    },
    "prepare and boil water": {"verb": "boil", "object": "the water"},
    "put the chicken pieces in an oven for about 10 minutes until cheese to melt": {
        "verb": "melt",
        "object": "the cheese",
    },
    "screw and fix the cover": {"verb": "screw", "object": "the cover"},
    "screw off the screws used to fix the switch": {
        "verb": "screw",
        "object": "the switch",
    },
    "soak and wash the rice": {"verb": "wash", "object": "the rice"},
    "stir the bowl until all the ingredients are combined": {
        "verb": "combine",
        "object": "the ingredients",
    },
    "tear off the front of the sticker": {"verb": "remove", "object": "the sticker"},
    "tear off the other side of the sticker": {
        "verb": "remove",
        "object": "the sticker",
    },
    "unscrew the screws used to fix the screen": {
        "verb": "unscrew",
        "object": "the screws",
    },
    "use the needle to open the SIM card slot": {
        "verb": "open",
        "object": "the SIM card slot",
    },
    "wet and wash hands": {"verb": "wash", "object": "the hands"},
    "wet and wash the hair": {"verb": "wash", "object": "the hair"},
    "mince cabbage and chop some green onions": {
        "verb": "chop",
        "object": "the onions",
    },
    "put the melted soap block into the vessel": {
        "verb": "fill",
        "object": "the vessel",
    },
    "add some cleaner to clean and wet the lenses and take out the lenses": {
        "verb": "clean",
        "object": "the lenses",
    },
    "mix in salt and pepper.": {"verb": "mix", "object": "the salt and pepper"},
    "banknote falling like a feather or paper": {
        "verb": "fall",
        "object": "the banknote",
    },
    "wrap with the new wrapper": {"verb": "wrap", "object": "the battery"},
    "paste patch": {"verb": "paste", "object": "the patch"},
    "screw off the valve cap and open the valve": {
        "verb": "open",
        "object": "the valve",
    },
    "let the jack down": {"verb": "let down", "object": "the jack"},
    "apply toothpaste or other cleaning agent to scratch": {
        "verb": "clean",
        "object": "the monitor",
    },
    "apply the shampoo or hair conditioner": {"verb": "wash", "object": "the hair"},
    "disinfect": {"verb": "clean", "object": "the arm"},
    "cover with some soil": {"verb": "cover", "object": "the hole"},
    "spoon falling like a rock": {"verb": "fall", "object": "the spoon"},
    "stamp falling like a rock": {"verb": "fall", "object": "the stamp"},
    "pull out after a period of time": {"verb": "pull", "object": "the injection"},
    "fill the solution to the mark": {"verb": "fill", "object": "the flask"},
    "pour the tea into the vessel": {"verb": "pour", "object": "the tea"},
    "pour the egg into the pot": {"verb": "fill", "object": "the pot"},
    "push the pin in": {"verb": "insert", "object": "the pin"},
    "pour the soultion to the volumetric flask": {
        "verb": "fill",
        "object": "the flask",
    },
    "pour the ingredients into the bowl": {"verb": "fill", "object": "the bowl"},
    "pour oil into the wok": {"verb": "fill", "object": "the wok"},
    "pour raw materials": {"verb": "fill", "object": "the bowl"},
    "pour the wax into the vessel": {"verb": "fill", "object": "the vessel"},
    "wipe the toothpaste": {"verb": "clean", "object": "the monitor"},
    "pour the mixture on the meat loaf": {"verb": "cover", "object": "the mixture"},
    "pour some oil into a hot pan": {"verb": "fill", "object": "the pan"},
    "inject to the muscular": {"verb": "empty", "object": "the shot"},
    "put in the plant": {"verb": "insert", "object": "the plant"},
    "stick with the tape and wrap": {"verb": "wrap", "object": "the box"},
    "fit on the filter": {"verb": "fit", "object": "the filter"},
    "unload the wheel": {"verb": "detach", "object": "the wheel"},
    "scratch scales": {"verb": "clean", "object": "the fish"},
    "do the first two jump": {"verb": "jump", "object": "the athlete"},
    "pour wine over the snails in a bowl": {"verb": "cover", "object": "the bowl"},
    "mix and pickle": {"verb": "mix", "object": "the ingredients"},
    "knot at the end of the bandage": {"verb": "tie", "object": "the bandage"},
    "stick or bind flower to the frame": {"verb": "attach", "object": "the flower"},
    "pour water to the tree": {"verb": "wet", "object": "the tree"},
    "tighten screws": {"verb": "screw", "object": "the screws"},
    "absorb liquid with the dropper": {"verb": "wet", "object": "the tissue"},
    "turn on the water tap to wash": {"verb": "empty", "object": "the sink"},
    "wipe adhesive and bedding layer": {"verb": "spread", "object": "the glue"},
    "absorb some ink slowly": {"verb": "fill", "object": "the fountain pen"},
    "wipe off the cleaning agent": {"verb": "clean", "object": "the surface"},
    "put yogurt, honey and other ingredients into the juicer` - object `the ingredients": {
        "verb": "fill",
        "object": "the juicer",
    },
    "push the pin in": {"verb": "insert", "object": "the pin"},
    "cut both ends and remove fruit seeds": {
        "verb": "pull out",
        "object": "the fruit seeds",
    },
    "apply the cleaning agent with towel evenly": {
        "verb": "clean",
        "object": "the surface",
    },
    "push curling": {"verb": "push", "object": "the stone"},
    "put the pin in": {"verb": "insert", "object": "the pin"},
    "remove the hamster from the hamster cage": {
        "verb": "pull out",
        "object": "the hamster",
    },
    "apply the detergent to bathtub": {"verb": "clean", "object": "the bathtub"},
    "pour the butter into the egg yolks": {
        "verb": "mix",
        "object": "the butter and egg yolks",
    },
    "pour oil into a hot pan and add chopped onions and laksa sauce": {
        "verb": "fill",
        "object": "the pan",
    },
    "pour the soup on bean sprouts and sprinkle parsley on top": {
        "verb": "cover",
        "object": "the bowl",
    },
    "shave carefully on the face": {"verb": "shave", "object": "the beard"},
    "pour the cooking oil into the wok and add curry powder": {
        "verb": "fill",
        "object": "the wok",
    },
    "pour the marinade onto the chicken and mix": {
        "verb": "mix",
        "object": "the marinade and chicken",
    },
    "use a knife to burst air pockets": {
        "verb": "deflate",
        "object": "the air pockets",
    },
    "pour buttermilk and hot sauce on the chicken.": {
        "verb": "cover",
        "object": "the buttermilk, hot sauce and chicken",
    },
    "pouring water into cup until it overflows": {
        "verb": "fill",
        "object": "the cup",
    },
    "lie down front panel": {"verb": "drop", "object": "the front panel"},
    "cut a certain length": {"verb": "cut", "object": "the cable"},
    "add some lemon grass, fish sauce, sugar, salt, chicken powder, chilli flakes, and stir it to combine": {
        "verb": "combine",
        "object": "the lemon grass and the fish sauce",
    },
    "combine the milk with the flour": {
        "verb": "combine",
        "object": "the milk and the flour",
    },
    "combine pepper sauce and melted butter in a bowl": {
        "verb": "combine",
        "object": "the pepper sauce and the butter",
    },
    "combine diced toamto and cucumber and sliced onions": {
        "verb": "combine",
        "object": "the onions, the cucumber and the tomato",
    },
    "fill second pot with peas, mint, salt, sugar, and water and boil": {
        "verb": "fill",
        "object": "the pot",
    },
    "fill the taco shells and top with sour cream, grated cheddar cheese, and chopped lettuce": {
        "verb": "fill",
        "object": "the taco shells",
    },
    "mix some cumin, cinnamon, black pepper, and paprika": {
        "verb": "mix",
        "object": "the cumin, cinnamon, black pepper, and paprika",
    },
    "mix paprika and pepper with the meat": {
        "verb": "mix",
        "object": "the parika, pepper and meat",
    },
    "mix soy sauce, sesame oil, sugar, finely chopped spring onions, and minced garlic": {
        "verb": "mix",
        "object": "the flour, baking soda, salt, and sugar",
    },
    "mix together an egg, butter, and butter milk": {
        "verb": "mix",
        "object": "the egg, butter, and butter milk",
    },
    "mix the lettuce with the sauce dressing and add parmesan cheese": {
        "verb": "mix",
        "object": "the lettuce and the dressing",
    },
    "mix the breadcrumbs with the meat": {
        "verb": "mix",
        "object": "the breadcrums and the meat",
    },
    "brush sauce or sprinkle seasoning": {
        "verb": "sprinkle",
        "object": "the seasoning",
    },
    "mix flour, ghee, and salt together": {
        "verb": "mix",
        "object": "the flour, ghee, and salt",
    },
    "mix hot sauce and melted butter together": {
        "verb": "mix",
        "object": "the sauce and butter",
    },
    "add korean red chili pepper flakes to the mixture and mix with hand": {
        "verb": "mix",
        "object": "the chili pepper flakes and mixture",
    },
    "mix swiss cheddar and monterey jack cheese together in a bowl": {
        "verb": "mix",
        "object": "the cheddar and cheese",
    },
    "mix ingredients in the bowl using a fork": {
        "verb": "mix",
        "object": "the ingredients",
    },
    "add flour, cornmeal, sugar, salt, and baking soda to bowl and mix": {
        "verb": "mix",
        "object": "the flour, cornmeal, sugar, salt, and soda",
    },
    "add flour, paprika, garlic powder, black pepper, and salt to a bag and mix together": {
        "verb": "mix",
        "object": "the flour, paprika, garlic powder, pepper, and salt",
    },
    "drain the spaghetti then mix it with the pancetta egg and cream": {
        "verb": "mix",
        "object": "the spaghetti, the pancetta, and the cream",
    },
    "close the sluice and empty and disconnect the water pipe": {
        "verb": "close",
        "object": "the sluice",
    },
    "tear the dried seaweed into smaller pieces and put them on a plate": {
        "verb": "cut",
        "object": "the seaweed",
    },
    "fix the new string on the head of the guitar": {
        "verb": "fix",
        "object": "the guitar string",
    },
    "clean up the interior of thepumpkin": {"verb": "clean", "object": "the pumpkin"},
    "slice the potato pumpkin and eggplant": {
        "verb": "slice",
        "object": "the potato, the pumpkin and the egglpant",
    },
    "slice the fish cakes, bean curd, and boiled eggs": {
        "verb": "slice",
        "object": "the fish cakes",
    },
    "slice the tomatoes onions and pickles": {
        "verb": "slice",
        "object": "the tomateos, the onions, and the pickles",
    },
    "slice a piece of cucumber and add with the salmon": {
        "verb": "slice",
        "object": "the cucumber",
    },
    "screw off the screws and sheetmetals and baffles on the both sides of the CD drive": {
        "verb": "screw",
        "object": "the sheetmetals",
    },
    "use screwdriver or electirc screwdriver to screw the wire in the wall into the screw of the new switch": {
        "verb": "screw",
        "object": "the wire",
    },
    "dropping ear plug carrying case in front of a water bottle": {
        "verb": "fall",
        "object": "the earplug carrying case",
    },
    "attaching mobile charger to plug socket": {
        "verb": "plug",
        "object": "the mobile charger and the plug socket",
    },
    "crack 2 eggs in a bowl": {"verb": "crack", "object": "the eggs"},
    "crack two eggs in a bowl": {"verb": "crack", "object": "the eggs"},
    "crack one egg in a bowl": {"verb": "crack", "object": "the egg"},
    "drop all the meatballs into the boiling pot of sauce and cook": {
        "verb": "drop",
        "object": "the meatballs",
    },
    "add apple sauce black pepper and sesame oil and whisk everything together": {
        "verb": "mix",
        "object": "the apple sauce, the pepper, and the sesame oil",
    },
    "add an egg and some milk and whisk everything quickly": {
        "verb": "mix",
        "object": "the egg and the milk",
    },
    "separate the egg white and egg yolk and whisk the egg whites": {
        "verb": "divide",
        "object": "the egg white and the egg yolk",
    },
    "add dijon mustard milk and salt to eggs and whisk it": {
        "verb": "mix",
        "object": "the milk and the eggs",
    },
    "beat an egg in a bowl and whisk some milk with it": {
        "verb": "mix",
        "object": "the eggs and the milk",
    },
    "break three eggs and add a little cream": {"verb": "break", "object": "the eggs"},
    "matchbox falling like a rock": {"verb": "fall", "object": "the matchbox"},
    "pour it into a glass": {"verb": "fill", "object": "the glass"},
    "pour into a glass": {"verb": "fill", "object": "the glass"},
    "add in some flour and milk and whisk it": {
        "verb": "mix",
        "object": "the flour and milk",
    },
    "lifting wood log up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the wood log",
    },
    "lifting glue stick up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the glue stick",
    },
    "lifting book up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the book",
    },
    "lifting firm plastic up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the firm plastic",
    },
    "lifting usb stick up completely, then letting it drop down": {
        "verb": "fall",
        "object": "usb stick",
    },
    "lifting sketch pen up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the sketch pen",
    },
    "lifting set of compasses up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the compasses",
    },
    "lifting candle up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the candle",
    },
    "lifting box tape up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the box tape",
    },
    "lifting hose head up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the hose head",
    },
    "lifting note pad up completely, then letting it drop down": {
        "verb": "fall",
        "object": "the note pad",
    },
    "plugging mains plug into socket": {"verb": "plug", "object": "the mains plug"},
    "wash and slice the prawn and add it to the meat": {
        "verb": "slice",
        "object": "the prawn",
    },
    "pour in the prepared dressing and mix again to serve": {
        "verb": "mix",
        "object": "the dressings",
    },
    "mix in cheese": {"verb": "mix", "object": "the cheese"},
    "mix in flour": {"verb": "mix", "object": "the flour"},
    "mix in tamarind paste": {"verb": "mix", "object": "the tamarind paste"},
    "flush and wash the interior": {"verb": "wash", "object": "the interior"},
    "separate and cut the chicken wing at the two joints": {
        "verb": "cut",
        "object": "the chicken wing",
    },
    "roll dough flat and cut into circles": {"verb": "cut", "object": "the dough"},
    "throwing throwing lighter in the air and letting it fall": {
        "verb": "fall",
        "object": "the lighter",
    },
    "whisk the eggs": {"verb": "whisk", "object": "the egg yolk and egg white"},
    "pull out the screen connector and remove the screen": {
        "verb": "unplug",
        "object": "the screen connector",
    },
    "reset and screw on the screws": {"verb": "screw", "object": "the screws"},
    "cut the head": {"verb": "remove", "object": "the head"},
    "insert it into the crystal head": {"verb": "insert", "object": "the cable"},
    "do facial care carefully": {"verb": "clean", "object": "the face"},
    "do the first layup": {"verb": "throw", "object": "the ball"},
    "do the third jump": {"verb": "rise", "object": "the athlete"},
    "put paper together": {"verb": "combine", "object": "the paper"},
    "put the sticker on the windows": {"verb": "attach", "object": "the sticker"},
    "put every parts mentioned together": {"verb": "combine", "object": "the parts"},
    "put all bed boxes together": {"verb": "collect", "object": "the bed boxes"},
    "put the filler on the bread slice": {"verb": "spread", "object": "the filler"},
    "put the waterproof cover": {"verb": "install", "object": "the waterproof cover"},
    "put on the sofa cover": {"verb": "install", "object": "the sofa cover"},
    "put on the tire": {"verb": "install", "object": "the tire"},
    "put on the hair extensions": {"verb": "install", "object": "the hair extensions"},
    "dip detergent with rag or apply detergent": {
        "verb": "dip",
        "object": "the detergent",
    },
    "dip detergent with rag": {"verb": "dip", "object": "the detergent"},
    "release liquid": {"verb": "empty", "object": "the pipette"},
    "chop the lemon grass ginger onion and chili finely": {
        "verb": "chop",
        "object": "the lemon grass",
    },
    "pour the sauce over the mussel shells": {
        "verb": "cover",
        "object": "the mussel shells",
    },
    "put the patties cheese sauce and vegetables in buns": {
        "verb": "put it",
        "object": "the patties",
    },
    "combine chicken stock dark soy sauce cooking wine hoisin sauce black vinegar sugar and sesame oil": {
        "verb": "combine",
        "object": "the ingredients",
    },
    "mix some corn starch and water together": {
        "verb": "mix",
        "object": "the corn starch and the water",
    },
    "pour eggs on the lobster": {"verb": "cover", "object": "the lobster"},
    "combine soy sauce mirin rice vinegar and honey": {
        "verb": "combine",
        "object": "soy sauce, mirin, rice vinegar and honey",
    },
    "pour the combined liquid and the blended pear to the green onion bowl": {
        "verb": "fill",
        "object": "the bowl",
    },
    "put cake flour sugar corn starch baking powder and salt in a bowl and sift them together": {
        "verb": "put in",
        "object": "the cake, flour, and sugar",
    },
    "mix the bowl well with a whisk": {"verb": "mix", "object": "the ingredients"},
    "mix some cornflour and water and add the mixture to the soup": {
        "verb": "mix",
        "object": "the cornflour and water",
    },
    "pat escargot dry and place on mat": {"verb": "dry", "object": "the escargot"},
    "place basil leaves in the soup": {"verb": "insert", "object": "the basil leaves"},
    "throwing usb stick against sofa": {"verb": "throw", "object": "the usb stick"},
    "leaves falling like a feather or paper": {"verb": "fall", "object": "the leaves"},
    "tearing paper into two pieces": {"verb": "cut", "object": "the paper"},
    "spread some chopped steamed lobster and sauteed shrimp on the dish": {
        "object": "the chopped lobster",
        "verb": "spread",
    },
    "covering comb with tissue": {"verb": "cover", "object": "the comb"},
    "drizzle oilive oil on the mixture": {"verb": "wet", "object": "the mixture"},
    "drain the water from the tofu box and slice the tofu into cubes": {
        "verb": "empty",
        "object": "the tofu box",
    },
    "mix in the pepper": {"verb": "mix", "object": "the pepper"},
    "pouring water onto the floor": {"verb": "wet", "object": "the floor"},
    "wiping water off of stool": {"verb": "clean", "object": "the stool"},
    "put on the shin guard sleeves or football socks": {
        "verb": "insert",
        "object": "the foot",
    },
    "taking usb flashdisk out of blue bowl": {
        "verb": "pull out",
        "object": "the usb stick",
    },
    "pushing id card so that it falls off the table": {
        "verb": "drop",
        "object": "the id card",
    },
    "separate the clams from the shells and chop them": {
        "verb": "separate",
        "object": "the clams",
    },
    "covering a pencil with a paper": {"verb": "cover", "object": "the pencil"},
    "soak sugar gourd in sugar": {"verb": "wet", "object": "sugar"},
    "pouring water onto countertop": {"verb": "wet", "object": "the countertop"},
    "tooth paste falling like a rock": {"verb": "fall", "object": "the tooth paste"},
    "add two bay leaves carrots celery and onions to the pan": {
        "verb": "insert",
        "object": "the bay leaves",
    },
    "absorb liquid with dropper": {"verb": "fill", "object": "the dropper"},
    "attach drawer back panel": {"verb": "attach", "object": "the drawer back panel"},
    "attaching pen drive to cd player": {"verb": "attach", "object": "the pen drive"},
    "boil a piece of kombu and a small bowl of bonito flakes in water in a pot": {
        "verb": "boil",
        "object": "the kombu",
    },
    "boil some onion chunks and baby boy chok in chicken stock with water": {
        "verb": "boil",
        "object": "the onion",
    },
    "boil the wontons in boiled water": {"verb": "boil", "object": "the wontons"},
    "boil water and the noodles in it": {"verb": "boil", "object": "the noodles"},
    "combine flour cornstarch instant mashed potatos and cayenne": {
        "verb": "combine",
        "object": "the flour and the potatos",
    },
    "combine lemon juice, sumac, garlic, salt, and oil in a bowl": {
        "verb": "combine",
        "object": "the lemon juice and the oil",
    },
    "combine the patties and cheese and season with salt and pepper": {
        "verb": "combine",
        "object": "the patties and the cheese",
    },
    "covering keys with cushion": {"verb": "cover", "object": "the keys"},
    "digging spoon out of powder": {"verb": "uncover", "object": "the spoon"},
    "digging tv remote out of cap": {"verb": "uncover", "object": "the tv remote"},
    "dropping lighter in front of statue": {"verb": "drop", "object": "the lighter"},
    "fit on the fuse": {"verb": "fit", "object": "the fuse"},
    "form each piece into a ball roll out and roll up": {
        "verb": "form",
        "object": "a ball",
    },
    "form the boxty into a ball": {"verb": "form", "object": "a ball"},
    "form the meat into a loaf on a baking sheet": {"verb": "form", "object": "a loaf"},
    "form the meat into a patty": {"verb": "form", "object": "a patty"},
    "form the meat into balls and fry": {"verb": "form", "object": "a ball"},
    "form the rice into a ball": {"verb": "form", "object": "a ball"},
    "grind all the ingredients and transfer to a bowl": {
        "verb": "combine",
        "object": "the ingredients",
    },
    "in a bowl combine ground beef bread crumbs cream beaten egg worcestershire sauce salt pepper and some beef broth": {
        "verb": "combine",
        "object": "the ingredients",
    },
}
