EXCLUDED = [
    "stick on the labels",
    "pour the egg onto the plate",
    "iron the cloths with the iron",
    "spinning hair brush that quickly stops spinning",
    "twine around the thread",
    "zeroing set",
    "spinning bottle spray that quickly stops spinning",
    "fit on the filter",
    "cut off the edge",
    "moving screwdriver set and toothpaste away from each other",
    "spinning maaza fruit drink that quickly stops spinning",
    "wipe the glue to a layer",
    "bake pizza",
    "approaching drink with your camera",
    "assemble the cushion and the backrest",
    "drink lid being deflected from tiles pieces",
    "moving pencil and wooden scale so they collide with each other",
    "put the sample to be measured on the balance",
    "pretending to poke paper rose",
    "put the weight until the balance is balanced",
    "calibrate the liquid",
    "trying to bend roller so nothing happens",
    "pull the ears outwards",
    "pushing body spray with car toy",
    "moving dove body spray and dettol bottle closer to each other",
    "turning body spray upside down",
    "turn the suspension link",
    "spray experimentally to check",
    "top with basil leaves",
    "tilting lunch box with snacks box on it slightly so it doesn't fall down",
    "shape cookie",
    "put the quilt on the bed",
    "fit on the boards",
    "use electricity meter to check the power supply",
    "buckle the cap",
    "spray towards the fire",
    "scrape tarpaulin without ink",
    "fit on the shell",
    "rub and drag the materials",
    "put the pillow on the bed",
    "set the underprop",
    "bent the paperclips by hand",
    "filtrate with a filter",
    "apply polishing paste on the surface",
    "flip the sandwich over and press down",
    "plunge into thight",
    "put rubber on paddle",
    "do artificial breathing to the patient",
    "nail down ot stick together",
    "set up brakcets",
    "install the scews and sheetmetals and baffles onto the hard disk tray",
    "carve along the outline",
    "grind roundly and evenly",
    "iron the cloths with the iron",
    "use the air pressure gun or hair drier to flatten the wrapper",
    "lay the cushion evenly",
    "trigger and take out the needle head",
    "flatten the dough",
    "place cushion and backrest",
    "putting letter that can't roll onto a slanted surface, so it slides down",
    "invert seasoning",
    "a little bit noodles",
    "take a little bit noodles and taste it",
    "collect blood",
    "add tomato puree and cook until it starts to lose oil",
    "after cooking mix well to incorporate cheese and then bake",
    "bake it in the oven for 10 minutes and they are ready to serve",
    "bake the bread in an oven",
    "brush each pizza bite with some melted butter and sprinkle some italian seasoning on top",
    "clean up and soak",
    "cut in half",
    "cut into small pieces",
    "cut into strips",
    "cut into strips and pieces",
    "cut a hole",
    "cut out a hole",
    "cut along the edges",
    "find the position of the hole",
    "fill with some soil",
    "pour in after mix it",
    "mix in sour cream",
    "leave the jars at the room temperature closing the lids not too tight for 5-6 days"
    "once it is cooled, add the chopped onions, grated cheddar, yougart, salt, pepper, and melted butter and mix well",
    "package and freeze",
    "place the tray under broiler and bake the meat balls until well browned"
    "pour in after mix it",
    "mix an egg worcester sauce mustard ketchip pepper onion bell pepper garlic salt and bread crumbs",
    "pour the noodles into the water and stir",
    "pour the cooked noodles",
    "put some of the vegetables in to the pot and let it come to boil by slightly separating the noodles",
    "putting 3 boxes onto metal cup",
    "putting a camera cover in front of letter s",
    "plugging data cable into laptop usb hole but pulling it right out as you remove your hand",
    "putting yellow coloured hair band next to charger adapter",
    "reset the switch and screw on the screws used to fix the switch",
    "reveal the glue from the face",
    "roll it up brush some paste on edge and close it to a roll",
    "use vacuum cleaner to clean",
    "melt the soap block",
    "pour some barbecue sauce on the meat loaf and bake the meatloaf",
    "prepare and boil water",
    "boil water or coffee",
    "tilting plan sheet with rubber on it slightly so it doesn't fall down",
    "trying to pour water into bottle, but missing so it spills next to it"
    "spoon colliding with spoon and both are being deflected",
    "a water can colliding with another water can and both are being deflected",
    "pour some glue to the face",
    "pour the sauce on top of the egg",
    "pour half of the liquid to the mixed vegetable",
    "pour some water to the soy milk maker",
    "toss everything well to combine",
    "combine flour, sugar, polenta, baking powder, egg, and milk",
    "mix soy sauce, sesame oil, sugar, finely chopped spring onions, and minced garlic",
    "add salt and garlic, powder seasoning, black pepper powder to the flour and mix well",
    "add cumin powder, red chili powder, and garlic powder and mix it well",
    "mix chicken breast, apple grape, celery, lemon juice, cream together and season with black pepper and salt."
    "fold the squares inward and fix them",
    "slice it diagonally and serve",
    "pour some soy beans",
    "mix the cooked bulgur wheat, boiled chickpeas, diced tomato, cucumber, leeks, and parsley",
    "lifting up one end of table without letting it drop down",
    "lifting jar up completely without letting it drop down",
    "lifting flashlight up completely without letting it drop down",
    "lifting up one end of box without letting it drop down",
    "lifting up one end of pencil without letting it drop down",
    "lifting up one end of a booklet without letting it drop down",
    "add anchovy paste worcestershire sauce olive oil and parmesan cheese and whisk it.",
    "pour into the ingredients",
    "moving moving something and close each other closer to each other",
    "cut off and remove the old string",
    "anchovy paste worcestershire sauce olive oil and parmesan cheese",
    "put the clothes neatly on a ironing table",
    "put nicely and align the quilt and the cover",
    "put and arrange nicely",
]
